# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24ef7d4439aaaaad9383f43d4d3b35bcbeaa0b4e0f94f927f2f63bcda1d3cb05f03f49503f7d0e1ae9be88d2d0ca472306a8c63ed5eaa1eb8f92738d82029a16

test:
  secret_key_base: 6ba17453a73585bc947c7922240c840685adf6f86978cf62926df21f0f00f54832d72dd3066d59aad15811a431f33e4d6b16dc8b280bb5094910ce93d5ca8151

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
